apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.frontend.serviceAccount.name }}
  namespace: {{ .Values.global.namespace }}
  {{- if .Values.frontend.serviceAccount.roleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.frontend.serviceAccount.roleArn }}
  {{- end }}
