apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.therapistService.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.therapistService.name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.therapistService.port }}
      targetPort: {{ .Values.therapistService.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.therapistService.name }}
